[package]
name = "hello"
version = "0.1.0"
authors = ["Tomislav Dukez <tomdu3@ymail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
